spring:
  application:
    name: authentication-service
  r2dbc:
    url: r2dbc:<url-data_base>
    username: NAME_USERNAME_DATABASE
    password: SECRET_PASSWORD
  flyway:
    enabled: true
    url: jdbc:<url-data_base>
    user: NAME_USERNAME_DATABASE
    password: SECRET_PASSWORD
    locations: classpath:db/migration

# Para JWT (ejemplo)
jwt:
  secret: SECRET_JWT
  expiration: 3600000   # 1 hora en milisegundos

# Configuración de logging
logging:
  level:
    root: INFO
    org.springframework: INFO